create or replace TRIGGER TRIGGER_CID_DRAMACONTENT BEFORE INSERT ON DRAMACONTENT
FOR EACH ROW 
BEGIN
    SELECT SEQUENCE_CID_DRAMACONTENT.NEXTVAL into :NEW.CID from Dual;
END;



create or replace TRIGGER TRIGGER_DRAMAID_DRAMACATEGORY BEFORE INSERT ON DRAMACATEGORY
FOR EACH ROW 
BEGIN
    SELECT SEQUENCE_DRAMAID_DRAMACATEGRY.NEXTVAL into :NEW.DRAMAID from Dual;
END;



create or replace TRIGGER TRIGGER_TIME_DRAMACONTENT BEFORE UPDATE ON DRAMACONTENT
FOR EACH ROW 
BEGIN
    IF :NEW.TITLE != :OLD.TITLE OR :NEW.STATUS != :OLD.STATUS THEN
       :NEW.UPLOAD_DATE := sysdate;
    END IF;
END;